config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount SimpleDiscussion::Engine => "/forum"

  get 'home/index'

  root to:  "jobs#index"

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :bigint           not null, primary key
#  company_name        :string
#  company_website     :string
#  compensation_range  :string
#  compensation_type   :string
#  estimated_hours     :string
#  featured            :boolean          default(FALSE)
#  featured_until      :datetime
#  headquarters        :string
#  link_to_apply       :string
#  price               :integer
#  published_at        :datetime
#  remote              :boolean          default(FALSE)
#  slug                :string
#  status              :string           default("pending")
#  title               :string
#  upsell_type         :string
#  years_of_experience :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_jobs_on_slug     (slug) UNIQUE
#  index_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord

  extend FriendlyId

  belongs_to :user

  has_rich_text :title
  has_rich_text :description
  has_rich_text :company_description

  has_one_attached :company_logo


  friendly_id :slug_candidates, use: [ :slugged, :finders ]

  def slug_candidates
    [:title, [:title, :company_name]]
  end

  def should_generate_new_friendly_id?
    if !slug?
      title_changed?
    else
      false
    end
  end


  # Scopes        method of call - Job::JOB_STATUSES[:pending]

  scope :desc, -> { order(created_at: :desc) }
  scope :pending, -> { where(status: JOB_STATUSES[:pending]) }
  scope :published, -> { where(status: JOB_STATUSES[:published]) }
  scope :archived, -> { where(status: JOB_STATUSES[:archived]) }

  JOB_STATUSES = {
    pending: "pending",
    published: "published",
    archived: "archived"
  }.freeze


  def pending?
    self.status == Job::JOB_STATUSES[:pending]
  end

  def published?
    self.status == Job::JOB_STATUSES[:published]
  end

  def archived?
    self.status == Job::JOB_STATUSES[:archived]
  end


# CONSTANTS

  COMPENSATION_TYPES = [
  "Contract position",
  "Full-time position"
  ]

  HOURLY_RANGES = [
    "less than 10",
    "10-30",
    "30-60",
    "60-90",
    "more than 100",
  ].freeze

  COMPENSATION_RANGES = [
    "50,000 - 60,000",
    "60,000 - 70,000",
    "70,000 - 80,000",
    "80,000 - 90,000",
    "90,000 - 100,000",
    "110,000 - 120,000",
    "120,000 - 130,000",
    "130,000 - 140,000",
    "140,000 - 150,000",
    "160,000 - 170,000",
    "170,000 - 180,000",
    "180,000 - 190,000",
    "190,000 - 200,000",
    "200,000 - 210,000",
    "210,000 - 220,000",
    "220,000 - 230,000",
    "230,000 - 240,000",
    "240,000 - 250,000",
    "greater than 250,000",
  ].freeze




end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @jobs = Job.all.published.desc
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def new_job
      if @job.updated_at?
        new_job = true
      else
        new_job = false
      end
    end

    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(
         :company_logo,
         :company_name,
         :company_website,
         :company_description,
         :compensation_range,
         :compensation_type,
         :description,
         :estimated_hours,
         :headquarters,
         :link_to_apply,
         :price,
         :remote,
         :role_type,
         :title,
         :upsell_type,
         :years_of_experience
      )
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true, multipart: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container ">
  <div class="justify-content-start  ">
    <%= form.label :company_logo, class: "form-label" %>
    <%= form.file_field :company_logo %>
    <span class="justify-content-end ">
      <% if form.object.company_logo.attached? %>
        <%= image_tag form.object.company_logo, style: "max-width: 60px", class: "input"%>
      <% end %>
    </span>
  </div>


  <div class="form-group">
    <%= form.label :title, class: "label" %>
    <%= form.rich_text_area :title, size: '48', class: "input" %>
  </div>


  <div class="form-group">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description, class: "input" %>
  </div>

  <div class="row ml-2">
    <div class="form-group">
      <%= form.label :company_name, class: "label" %> <br>
      <%= form.text_field :company_name, size: '48', class: "input" %>
    </div>

    <div class="form-group ">
      <%= form.label :link_to_apply, class: "label" %> <br>
      <%= form.text_field :link_to_apply, size: '48', class: "input" %>
    </div>
  </div>

  <div class="row ml-2">
    <div class="form-group">
      <%= form.label :company_website, class: "label" %><br>
      <%= form.text_field :company_website, size: '48', class: "input" %>
    </div>

    <div class="form-group ">
      <%= form.label :headquarters, class: "label" %> <br>
      <%= form.text_field :headquarters, size: '48', class: "input" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :company_description, class: "label" %>
    <%= form.rich_text_area :company_description, class: "input" %>
  </div>

  <div class="row ml-2">

    <div class="form-group  mr-4">
      <%= form.label :compensation_range, class: "label" %><br>
      <%= form.text_field :compensation_range, size: '16', class: "input" %>
    </div>

    <div class="form-group mr-4">
      <%= form.label :estimated_hours, class: "label" %><br>
      <%= form.text_field :estimated_hours, size: '10', class: "input" %>
    </div>

    <div class="form-group mr-4">
      <%= form.label :years_of_experience, class: "label" %><br>
      <%= form.text_field :years_of_experience, size: '4', class: "input ml-4" %>
    </div>


    <div class="form-group  mr-4">
      <%= form.label :compensation_type, class: "label" %> <br>
      <%= form.select :compensation_type, Job::COMPENSATION_TYPES,{}, { class: "select" } %>
    </div>

    <div class="form-group ml-4">
      <br>
      <%= form.check_box :remote, class: "input " %>
      <%= form.label :remote, class: "label" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit class: "ml-2 btn btn-sm btn-success font-weight-bold" %>
  </div>

<% end %>
</div>

app/views/jobs/_job.html.erb
<div class="container relative text-dark mt-4 ml-4 ">
  <div class="card">
    <div class="justify-content-start">
      <% if job.company_logo.attached? %>
          <%= image_tag job.company_logo.variant(resize_to_fit: [24, 24]), class: "" %>
      <% end %>
      <span class="font-weight-bold text-dark"><%= job.company_name %></span>
    </div>

    <div class="d-flex justify-content-end mr-2 mt-0">
      <% if admin? %>
        <%= link_to 'Edit', edit_job_path(job) , class: "btn btn-sm btn-outline-dark mr-3 font-weight-bold px-3" %>
        <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>

    <div>
      <% if job.featured? %>
        <span class="p-2  ml-4  rounded-pill bg-warning font-weight-bold">Featured</span>
      <% end %>
    </div>

    <p><%= link_to job.title, job_path(job_id = job.id), class: "job-title"   %></p>

    <p class="mb-0 font-weight-bold">
      <%= job.compensation_type %> <span class="p-2">&bull;</span>
      <% if job.compensation_type.downcase == "contract" %>
        <%= job.estimated_hours %> hours
      <% else %>
        <%= number_to_currency(job.compensation_range) %><span class="p-2">&bull;</span>
        <%= pluralize(job.years_of_experience, 'year') %> of experience
      <% end %>
    </p>
    <p>
      <% if job.remote? %>
        Remote &bull;
      <% end %>
      <%= job.headquarters %>
    </p>
  </div>
</div>

app/views/jobs/_job2.html.erb
<div class="row">
  <div class="col-9">
    <h4><%= link_to job.title, job_path(job_id = job.id)   %></h4>
  </div>

  <div class=" d-flex items-right mx-3 mb-3">
    <%= render_svg "icons/pointer" %> <span class="ml-3"><%= job.description %></span>
  </div>


  <div class="col-3">
    <% if job.company_logo.attached? %>
      <%= image_tag job.company_logo, class: "w-28 h-28" %>
    <% end %>
  </div>
</div>

<div class="row">
  <h6 class="col-6">
    <strong><%= image_tag("icons/your_logo1.png", size: "30x30") %> <%= job.company_name %>  Company</strong>
  </h6>
  <p class="col-6">
    <strong>Headquarters</strong> <%= job.headquarters %>
  </p>
</div>

<div class="row">
  <p class="col-4">
    <strong>Salary Range:  </strong> <%= job.compensation_range %>
  </p>
  <p class="col-4">
    <strong>Desired Experience:  </strong> <%= job.years_of_experience %>
  </p>

  <p class="col-4">
    <strong class="list-inline">Location</strong>
    <% if job.remote?  %>
      Remote
    <% else %>
      <%= job.headquarters %>
    <% end %>
  </p>

</div>

<% if admin? %>
  <%= link_to 'Edit', edit_job_path(job) , class: "btn btn-sm btn-outline-dark mr-3" %>
  <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-sm btn-outline-danger" %>
<% end %>
<hr>

app/views/jobs/edit.html.erb
<div class="container">
  <h3 class="text-center ">  Edit your job  </h3>


  <%= render 'form', job: @job %>
  <div>
    <%= link_to 'Show', @job , class: "btn btn-sm btn-outline-primary ml-2 mr-3" %>
    <%= link_to 'Back', jobs_path , class: "btn btn-sm btn-outline-dark"%>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
<%= content_for :hero do %>

    <div class=" flex flex-wrap text-center text-white bg-danger ml-4 ">
      <h1 class="font-weight-bold pt-3 p-2">Find a Ruby on Rails developer</h1>
      <p class="font-weight-bold">The internet's resource for Ruby on Rails developers</p>
      <%= link_to "Find a developer", "#" ,  class: "btn btn-sm btn-outline-light border rounded mr-3  mb-4" %>
      <%= link_to "Find a job", "#" ,  class: "btn btn-sm btn-secondary px-4 border border-dark rounded mb-4" %>
      <%= link_to "Community portal", "#" ,  class: "btn btn-sm btn-light border border-dark rounded ml-3 mb-4" %>
    </div>
  </div>
<% end %>


  <%= render @jobs %>


</div>

app/views/jobs/new.html.erb
<div data-controller="jobs">
  <div data-jobs-target="mount"></div>
</div>

app/views/jobs/show.html.erb
<div class="container">

  <div class="">
    <%= link_to root_path, class: "mb-3 d-inline-flex items-center justify-start group" do %>
      <%= render_svg "icons/chevron-left" %>
      <span class="show-view ">Back to all jobs</span>
    <% end %>
  </div>

  <div class="">
    <div class="">
      <%= link_to @job.company_name, @job.company_website, class: "grid nav-bar-extras ", style: "font-size: 20px" %>

      <h2 class="mb-2 text-3xl "><%= @job.title %></h2>

      <p class="pb-3 mb-3 font-weight-bold ">
        <%= @job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
        <% if @job.compensation_type.downcase == "contract" %>
          <%= @job.estimated_hours %> hours
        <% else %>
          <%= number_to_currency(@job.compensation_range) %> <span class="px-px text-gray-600">&bull;</span> <%= pluralize(@job.years_of_experience, 'year') %> of experience
        <% end %>
        <% if @job.remote? %>
          &bull;<span class="ml-1">Work from home</span>
        <% else %>
          &bull;<span class="ml-1">Office Location: </span><%= @job.headquarters %>
        <% end %>
      </p>

      <h3 class="mb-2 ">About the role</h3>
      <div class="prose">
        <%= @job.description %>
      </div>

      <h3 class="mt-10 mb-2 text-xs font-bold tracking-wider text-gray-800 uppercase">About the company</h3>
      <div class="mb-6 prose">
        <%= @job.company_description %>
      </div>

      <%= link_to "Apply for this role", @job.link_to_apply, class: "btn btn-danger font-weight-bold px-2 py-3 mt-2" %>

      <% if author_of(@job) || admin? %>
        <%= link_to 'Edit this job', edit_job_path(@job), class: "btn btn-sm btn-outline-dark ml-2 block mt-6 p-3 mt-1" %>
      <% end %>
    </div>
    <div class="mb-10 text-center lg:col-span-4">
      <div class="sticky top-0 p-6 mt-6 text-gray-700 bg-white border-2 border-black rounded-lg shadow-sm">
        <% if @job.company_logo.attached? %>
          <div class="flex justify-center">
            <div class="w-16 h-16 my-3 text-center">
              <%= image_tag @job.company_logo.variant(resize_to_fit: [150, 150]), class: "flex-shrink-0 rounded-full " %>
            </div>
          </div>
        <% end %>
        <p><%= link_to @job.company_name, @job.company_website, class: "grid nav-bar-extras", style: "font-size: 20px"%></p>
        <p class="mb-2"><%= @job.title %></p>
        <p class="pb-3 mb-3">
          <%= @job.compensation_type %> <span class="">&bull;</span>
          <% if @job.compensation_type.downcase == "contract" %>
            <%= @job.estimated_hours %> hours </br>
        <% else %>
          <%= number_to_currency(@job.compensation_range) %> </br> <%= pluralize(@job.years_of_experience, 'year') %> of experience desired
      <% end %>
    </p>
    <%= link_to "Apply for this role", @job.link_to_apply, class: "btn btn-outline-danger px-2 py-3" %>
  </div>
</div>
</div>
</div>

app/views/jobs/show2.html.erb
<div class="card ml-4">
 <h3 class="flex text-center">  <%= @job.title %>  </h3>

<div class="card-body">

<p>
  <strong>Job description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @job.company_name %>
</p>

<p>
  <strong>Company website:</strong>
  <%= @job.company_website %>
</p>

<p>
  <strong>Company description:</strong>
  <%= @job.company_description %>
</p>

<p>
  <strong>Link to apply:  </strong>
  <%= @job.link_to_apply %>
</p>


<p>
  <strong>Compensation type:</strong>
  <%= @job.compensation_type %> position
</p>

<p>
  <strong>Compensation range $:</strong>
  <%= @job.compensation_range %>
</p>

<p>
  <strong>Estimated hours</strong>
  <%= @job.estimated_hours %>
</p>

<% if @job.remote? %>
<p>
  <strong>Remote:</strong>
  <%= @job.remote %>
</p>
<% else %>
<p>
  Not a remote position at this time
</p>
<% end %>

<p>
  <strong>Years of experience:</strong>
  <%= @job.years_of_experience %>
</p>

<p>
  <strong>User:</strong>
  <%= @job.user_id %>
</p>

<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-sm btn-outline-primary mr-3" %>
<%= link_to 'Back', jobs_path , class: "btn btn-sm btn-outline-dark"%>

</div>
</div>