config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount SimpleDiscussion::Engine => "/forum"

  get 'home/index'

  root to:  "jobs#index"

end

app/views/shared/_flash_notice.html.erb
<div id="flash-messages">
  <% flash.each do |type, message| %>
    <% if type == "alert" %>
        <div class="container bg-danger px-2 py-4 mx-auto font-sans font-medium text-center text-white">
          <%= message %>
        </div>
    <% end %>

    <% if type == "notice" %>
      <div class="container bg-success px-2 py-4 mx-auto font-sans font-medium text-center text-white">
        <%= message %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_left_nav.html.erb
<%= link_to root_path, class:"navbar-brand change-my-color  " do %>
  <%= render_svg "icons/railsdevs-mark", title: "railsdevs.com", styles: "fill-current " %>

  <span class="ml-2 font-weight-bold  text-danger">devjob</span>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md border border-danger rounded mx-4 mb-4 mt-2 pb-2 nav-bar">
  <div class="container">

    <%= link_to root_path, class:"navbar-brand change-my-color  " do %>
      <%= render_svg "icons/railsdevs-mark", title: "railsdevs.com", styles: "fill-current " %>
      <span class="ml-2 font-weight-bold  text-danger">devjob</span>
    <% end %>

    <button class="navbar-toggler navbar-dark " type="button" data-toggle="collapse" data-target="#navbarMenu" >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if user_signed_in? %>
        <li class="nav-item">
          <% if current_user.employer? %>
          <%= link_to 'New Job', new_job_path , class: "mx-4 btn btn-sm btn-info" %>
          <% end %>
        </li>
        <div class="d-none d-lg-block">
            <span class="nav-bar-extras pt-2 text-end ">
              Welcome: <%= current_user.first_name unless nil?   %>
            </span>
          </div>
            <%= link_to "Account", edit_user_registration_path, class: "btn btn-sm btn-outline-dark ml-4 mr-4" %>
            <%=  link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary mr-4" %>
          <% else %>
            <span class="nav-bar-extras p-1 text-end mr-4">
              Welcome: Guest
            </span>
            <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:" btn btn-sm btn-outline-primary" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-outline-primary" %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/shared/_right_nav.html.erb
<div class="collapse navbar-collapse">
  <ul class="navbar-nav ml-auto">
    <li class nav-item>
      <%= link_to 'New Job', new_job_path , class: "mx-4 btn btn-sm btn-success" %>
    </li>

    <li class nav-item>
      <% if user_signed_in? %>
        <span class="nav-bar-extras text-end">
          Welcome <%= current_user.email  %>
        </span>
        <%= link_to "Account", edit_user_registration_path, class: "btn btn-sm btn-outline-dark ml-4 mr-4" %>
        <%=  link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary mr-4" %>

      <% else %>
        <%= link_to "Login", new_user_session_path, class:"btn btn-sm btn-outline-primary" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-outline-primary" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_select_arrow.html.erb
<div class="absolute inset-y-0 right-0 flex items-center  ">
  <svg class="w-2 h-2 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
</div>

app/views/shared/_spacer.html.erb
<hr/>

app/views/shared/_test_nav.html.erb
<nav class="navbar navbar-expand-lg ">
  <%= link_to "devjob", root_path, class:"navbar-brand " %>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
      <li class nav-item>
        Welcome <%= current_user.email  %>
      </li>
      <li class nav-item>
        jobs <%= current_user.id %>
      </li>

    </ul>
  </div>
</nav>